### ISSUE TITLE
Can't handle some names, Problem with "..."

### ISSUE THREAD

**Issue by MythodeaLoL** [platelminto/parse-torrent-name#41]
https://www.themoviedb.org/movie/836946
`Eu.gosto.do.Homem-Aranha.....e.dai.1080p.AAC2.0.H264.mkv`
result:
```
{
  ["resolution"]=>
  string(5) "1080p"
  ["codec"]=>
  string(5) "H.264"
  ["audio"]=>
  string(7) "AAC 2.0"
  ["filetype"]=>
  string(3) "MKV"
  ["language"]=>
  string(7) "English"
  ["title"]=>
  string(24) "Eu gosto do Homem-Aranha"
  ["encoder"]=>
  string(3) "dai"
}
```
**title expected:** `Eu gosto do Homem-Aranha... e dai`

**and**

https://www.themoviedb.org/movie/42950
`What.If...2010.1080p.WEB-DL.DDP2.0.H264.mkv `
result:
```
{
  ["year"]=>
  int(2010)
  ["resolution"]=>
  string(5) "1080p"
  ["quality"]=>
  string(6) "WEB-DL"
  ["codec"]=>
  string(5) "H.264"
  ["audio"]=>
  string(22) "Dolby Digital Plus 2.0"
  ["filetype"]=>
  string(3) "MKV"
  ["title"]=>
  string(7) "What If"
}
```
**title expected:** `What If...`

Could you add a parse so if there are 3 dots "..." it ignores the removal or if there are more than 3 dots together, and leave only the 3 dots removing the others and adding a space if there is still the rest of the title? in case there is still a title after the 3 dots, could you leave the text together?

**Sample:** 

> `What.If...`
> What If...
> 
> `tick.tick...BOOM`
> tick tick...BOOM
> 
> `Se.Algo.Acontecer....Te.Amo`
> Se Algo Acontecer... Te Amo

I believe that with these changes the parse would be more accurate and closer to the original name. although I mostly use it for English, I found this problem with a title in Portuguese.

in case you can't update the code with these fixes, could you help me implement this? @platelminto 👍

**Comment by platelminto** [comment]
Hmmm I think this is definitely doable, I'll look into it. Thanks for opening an issue!

**Comment by platelminto** [comment]
Hey, sorry it's been a while - I've fixed this on the dev branch, and should push it to main/PyPI soon. Unfortunately, the first title you gave also triggers a separate bug (#42) - we'll see if I manage to fix this with this release.
