### ISSUE TITLE
Dont find episodeName for Show (between date and quality)

### ISSUE THREAD

**Issue by MythodeaLoL** [platelminto/parse-torrent-name#44]
`Lollapalooza.2022.Cat.Dealers.1080p.WEB-DL.AAC2.0.x264.mkv`

PTN doesn't know how to handle cases like this, where there is an **episodeName** between date and quality.

How could I take this `Cat.Dealers` value and insert it into **episodeName** ?
Would you have an option to put exclusion conditions for the capture of this episodeName in these date conditions => quality? For example, if it has the word `Chapter`, it ignores capturing the **episodeName**.

Expected result for `Lollapalooza.2022.Cat.Dealers.1080p.WEB-DL.AAC2.0.x264.mkv`
```
{
  ["year"]=>  int(2022)
  ["resolution"]=>  string(5) "1080p"
  ["quality"]=>  string(6) "WEB-DL"
  ["codec"]=>  string(5) "H.264"
  ["audio"]=>  string(7) "AAC 2.0"
  ["filetype"]=>  string(3) "MKV"
  ["title"]=>  string(12) "Lollapalooza"
  ["episodeName"]=>  string(11) "Cat Dealers"
}
```

Expected result for `Lollapalooza.2022.Chapter.1.Cat.Dealers.1080p.WEB-DL.AAC2.0.x264.mkv`
Ignoring episodeName because apply filter for texts `Chapter`.
```
{
  ["year"]=>  int(2022)
  ["resolution"]=>  string(5) "1080p"
  ["quality"]=>  string(6) "WEB-DL"
  ["codec"]=>  string(5) "H.264"
  ["audio"]=>  string(7) "AAC 2.0"
  ["filetype"]=>  string(3) "MKV"
  ["title"]=>  string(12) "Lollapalooza"
  ["excess"]=>  string(21) "Chapter 1 Cat Dealers"
}
```

I really need this fix, thanks if you can make a change. @platelminto @davidvuong

**Comment by platelminto** [comment]
Hey, it's been a while. This should be now fixed in `dev`, and pushed to main/PyPI soon.
