### ISSUE TITLE
Thread-safe parse

### ISSUE THREAD

**Issue by NebN** [platelminto/parse-torrent-name#49]
`PTN.parse` is not thread-safe.
The `PTN` object is created once in the module's **__init__.py** and shared across threads.
I don't know how costly creating a new `PTN` object is, but I figure it should be easy to test. If the performance is negligible, this method could be added to easly (albeit not elegantly) solve the issue of thread safety:

```
# TODO change coherent_types default to True in 3.0
def parse_threadsafe(name, standardise=True, coherent_types=False):
    return PTN().parse(name, standardise, coherent_types)
```

**Comment by platelminto** [comment]
Hey, seems easy enough to fix - I'll look into it as soon as I can!

**Comment by platelminto** [comment]
Fixed in dev, will publish in new PyPI release soon.
