### ISSUE TITLE
language subtitle should be array

### ISSUE THREAD

**Issue by the-rarbg** [platelminto/parse-torrent-name#56]
i think array would make more sense, for language, and subtitle, as whole.
example:  some time language is array as in 'Saving Private Ryan Salvate il soldato Ryan 1998 AC3 5 1 ITA ENG 2160p H265 HDR10 sub ita eng Sp'

but some times its single and give result as character 'English'  thats a bit inconsistant

**Comment by platelminto** [comment]
Hey, there's already a flag for this: `coherent_types`! See [this part](https://github.com/platelminto/parse-torrent-title#types-of-parts) of the README.

Let me know if it's what you're looking for and I can close this issue.
