### ISSUE TITLE
some issues with titles

### ISSUE THREAD

**Issue by the-rarbg** [platelminto/parse-torrent-name#57]
- The.Santa.Clause.1994-2006.Trilogy.1-3.720P.H265-Zero00
{'year': 2006,
 'resolution': '720p',
 'codec': 'H.265',
 'title': 'The Santa Clause 1994',
 'excess': 'Trilogy.1-3',
 'encoder': 'Zero00'}

- Planet.of.the.Apes.Collection.2001-2017.1080p.Fra.Eng
-{'year': 2017,
 'resolution': '1080p',
 'language': 'English',
 'title': 'Planet of the Apes Collection 2001',
 'encoder': 'Fra'}

**Comment by platelminto** [comment]
Covered by #20, will take a look at this soon (though no promises!). Added these examples to the issue.
